# Generated by Django 3.2.12 on 2023-01-28 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField()),
                ('product_name', models.CharField(max_length=100)),
                ('product_quantity', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='login',
            old_name='Email',
            new_name='Name',
        ),
    ]
