# Generated by Django 3.2.12 on 2023-01-30 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20230128_0802'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
