# Generated by Django 3.2.12 on 2023-02-06 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20230206_1209'),
    ]

    operations = [
        migrations.CreateModel(
            name='tempmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('you', models.CharField(max_length=100)),
            ],
        ),
    ]
