# Generated by Django 3.2.12 on 2023-02-06 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_tempmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tempmodel',
        ),
    ]
