# Generated by Django 3.2.12 on 2023-02-07 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_orders_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='items_json',
        ),
    ]
